site_name: HCBench
repo_url: https://compbioclub.github.io/HCBench
nav:
  - Home: index.md
  - Parsers:
      - CHISEL: parsers/chisel.md
      - SEACON: parsers/seacon.md
      - SIGNALS: parsers/signals.md
      - CNRein: parsers/cnrein.md
      - Alleloscope: parsers/alleloscope.md
  - GTbench:
      - Overview: gtbench/index.md
theme:
  name: material
